const fs = require("fs");
const path = require("path");
let PNG = null;
try {
    ({ PNG } = require("pngjs"));
} catch {
    // Model regeneration does not require pngjs. Keep the checked-in motion
    // texture when this optional asset-tool dependency is unavailable.
}

const projectRoot = path.resolve(__dirname, "..");
const modelDirectory = path.join(
    projectRoot,
    "src/main/resources/assets/syringe_mod/models/block");
const textureDirectory = path.join(
    projectRoot,
    "src/main/resources/assets/syringe_mod/textures/block/potion_mixing_table");

const idleModelPath = path.join(modelDirectory, "potion_mixing_table.json");
const activeModelPath = path.join(modelDirectory, "potion_mixing_table_active.json");
const motionTexturePath = path.join(
    textureDirectory, "potion_mixing_table_rotor_motion.png");
const motionMetadataPath = `${motionTexturePath}.mcmeta`;

const model = JSON.parse(fs.readFileSync(idleModelPath, "utf8"));
const hinge = [8.2, 9.75, 13.05];
const lidElementNames = new Set([
    "lid_frame_left",
    "lid_frame_right",
    "lid_frame_top",
    "lid_frame_bottom",
    "gasket_left",
    "gasket_right",
    "gasket_top",
    "gasket_bottom",
    "lid_glass_panel"
]);
const rotorElementPattern = /^(hub_|arm_|ampoule_)/;

function roundCoordinate(value) {
    return Math.round(value * 10000) / 10000;
}

function closeLidElement(element) {
    const corners = [];
    for (const x of [element.from[0], element.to[0]]) {
        for (const y of [element.from[1], element.to[1]]) {
            for (const z of [element.from[2], element.to[2]]) {
                corners.push([
                    x,
                    hinge[1] + (z - hinge[2]),
                    hinge[2] - (y - hinge[1])
                ]);
            }
        }
    }

    element.from = [0, 1, 2].map(axis =>
        roundCoordinate(Math.min(...corners.map(corner => corner[axis]))));
    element.to = [0, 1, 2].map(axis =>
        roundCoordinate(Math.max(...corners.map(corner => corner[axis]))));
    delete element.rotation;
}

model.credit = "Made with Blockbench; active state generated by project tool";
model.textures["16"] =
    "syringe_mod:block/potion_mixing_table/potion_mixing_table_rotor_motion";
model.elements = model.elements.filter(element => !rotorElementPattern.test(element.name));
for (const element of model.elements) {
    if (lidElementNames.has(element.name)) {
        closeLidElement(element);
    }
}
model.elements.push({
    name: "rotor_motion_overlay",
    from: [5.05, 9.7, 6.4],
    to: [11.9, 9.72, 11.6],
    faces: {
        up: {
            uv: [0, 0, 16, 16],
            texture: "#16"
        }
    }
});

fs.writeFileSync(activeModelPath, `${JSON.stringify(model, null, 2)}\n`, "utf8");

if (!PNG) {
    console.log(JSON.stringify({
        activeModel: activeModelPath,
        activeElements: model.elements.length,
        motionTexture: "preserved (pngjs unavailable)"
    }, null, 2));
    process.exit(0);
}

const FRAME_SIZE = 16;
const FRAME_COUNT = 4;
const texture = new PNG({
    width: FRAME_SIZE,
    height: FRAME_SIZE * FRAME_COUNT,
    colorType: 6
});
texture.data.fill(0);

const colors = {
    rotor: [61, 71, 76, 255],
    rotorLight: [87, 101, 107, 255],
    center: [28, 34, 38, 255],
    cyan: [33, 183, 193, 255],
    cyanLight: [113, 213, 212, 255],
    purple: [130, 65, 167, 255]
};

function pixel(frame, x, y, color) {
    if (x < 0 || y < 0 || x >= FRAME_SIZE || y >= FRAME_SIZE) return;
    const index = ((frame * FRAME_SIZE + y) * FRAME_SIZE + x) * 4;
    texture.data[index] = color[0];
    texture.data[index + 1] = color[1];
    texture.data[index + 2] = color[2];
    texture.data[index + 3] = color[3];
}

function rectangle(frame, x, y, width, height, color) {
    for (let py = y; py < y + height; py++) {
        for (let px = x; px < x + width; px++) {
            pixel(frame, px, py, color);
        }
    }
}

function sample(frame, x, y, color) {
    rectangle(frame, x - 1, y - 1, 3, 3, colors.rotorLight);
    rectangle(frame, x, y, 2, 2, color);
}

function drawCardinalFrame(frame, swapColors) {
    rectangle(frame, 7, 3, 2, 10, colors.rotor);
    rectangle(frame, 3, 7, 10, 2, colors.rotor);
    const vertical = swapColors ? colors.purple : colors.cyan;
    const horizontal = swapColors ? colors.cyan : colors.purple;
    sample(frame, 7, 2, vertical);
    sample(frame, 12, 7, horizontal);
    sample(frame, 7, 12, vertical);
    sample(frame, 2, 7, horizontal);
}

function drawDiagonalFrame(frame, swapColors) {
    rectangle(frame, 6, 6, 2, 2, colors.rotor);
    rectangle(frame, 8, 8, 2, 2, colors.rotor);
    rectangle(frame, 8, 6, 2, 2, colors.rotor);
    rectangle(frame, 6, 8, 2, 2, colors.rotor);
    rectangle(frame, 4, 4, 3, 2, colors.rotor);
    rectangle(frame, 9, 4, 3, 2, colors.rotor);
    rectangle(frame, 4, 10, 3, 2, colors.rotor);
    rectangle(frame, 9, 10, 3, 2, colors.rotor);
    const firstDiagonal = swapColors ? colors.purple : colors.cyan;
    const secondDiagonal = swapColors ? colors.cyan : colors.purple;
    sample(frame, 3, 3, secondDiagonal);
    sample(frame, 11, 3, firstDiagonal);
    sample(frame, 11, 11, secondDiagonal);
    sample(frame, 3, 11, firstDiagonal);
}

for (let frame = 0; frame < FRAME_COUNT; frame++) {
    if ((frame & 1) === 0) {
        drawCardinalFrame(frame, frame === 2);
    } else {
        drawDiagonalFrame(frame, frame === 3);
    }
    rectangle(frame, 6, 6, 4, 4, colors.rotorLight);
    rectangle(frame, 7, 7, 2, 2, colors.center);
    pixel(frame, 6, 6, colors.cyanLight);
}

fs.writeFileSync(motionTexturePath, PNG.sync.write(texture));
fs.writeFileSync(
    motionMetadataPath,
    `${JSON.stringify({ animation: { frametime: 2, interpolate: false } }, null, 2)}\n`,
    "utf8");

console.log(JSON.stringify({
    activeModel: activeModelPath,
    activeElements: model.elements.length,
    motionTexture: motionTexturePath,
    textureSize: [texture.width, texture.height],
    frames: FRAME_COUNT
}, null, 2));
